### ISSUE TITLE
Sass eq mixin

### ISSUE THREAD

**Issue by christianmagill** [Snugug/eq.js#57] opened 2015-08-19 20:30 UTC
I'm having some problems with the eq sass mixin.

Using the following code

.testing{
  padding: 10px;
  background: #f3f3f3;
  @include eq-pts((
      small: 400,
      medium: 500,
      large: 700
  ));
  @include eq(small){
    background: lighten(blue, 50%);
  }
  @include eq(medium){
    background: lighten(green, 50%);
  }
  @include eq(large){
    background: lighten(red, 50%);
  }
}

The CSS output is.

.testing{padding:10px;background:#f3f3f3;}
.testing:before{display:none;content:"small: 400, medium: 500, large: 700"}
.testing .testing[data-eq-state$=small]{background:#fff}
.testing .testing[data-eq-state$=medium]{background:#80ff80}
.testing .testing[data-eq-state$=large]{background:#fff}

This of course stops it from working.

Using gulp-sass 2.0.4 and eq.js 1.7.1

**Comment by Snugug** [comment] 2015-08-19 20:43
Duplicate of https://github.com/Snugug/eq.js/issues/48

**Closed as completed by Snugug** 2015-08-19 20:43 UTC
