### ISSUE TITLE
Add multiple values to data-eq-state when more than one is true

### ISSUE THREAD

**Issue by thomasdobber** [Snugug/eq.js#17] opened 2014-04-24 23:52 UTC
For example, when an element has a small, medium and large state and medium is true, small should also be added to data-eq-state as it is also true.

**Comment by Snugug** [comment] 2014-04-25 10:55
There are two issues that need to be addressed here, the first is being able to target a specific state (and only that state), and the second is being able to target a range of states. Because of how attribute selectors work, if we had `<div data-eq-state="small medium"></div>`, the selector we would  need to use to target `medium` would be `[data-eq-state~="medium"]`. Problem is, when we move to  `<div data-eq-state="small medium large"></div>`, we need to use the same selector. This means that if we have changes we don't want carried over, we need to either override them in `large`, creating fragile systems, or we need to have a way to `just` target `large`. While this is doable by switching up our selector from `[data-eq-state~="medium"]` to `[data-eq-state$="medium"]`, that selector isn't backwards compatible with IE8 (neither is `~=`, btw). On the other hand, if state is a simple single value, we can comma-separate in our CSS and achieve effectively the same thing, with full compatibility (which is the recommended thing to do now).

This all in mind, I'm not necessarily opposed to adding a `data-eq-matches` (or something similar) that will contain all of the states it matches, but that's starting to become a lot of things `eq.js` writes to the DOM.

**Comment by thomasdobber** [comment] 2014-04-29 10:48
How about just leaving instructions to conditionally load a attribute selector polyfill like http://selectivizr.com/ ?

Example: 

```
<!--[if (gte IE 6)&(lte IE 8)]>
  <script type="text/javascript" src="selectivizr.js"></script>
<![endif]-->
```

**Comment by Snugug** [comment] 2014-04-29 10:51
Selectivizer is incredibly unperformant, I don't recommend using it at all. I've had IE8 explode from a standard smattering of advanced attribute selectors, and as this is entirely attribute selector powered, I'd not want to pair the two

**Comment by thomasdobber** [comment] 2014-04-29 12:51
How about using something like http://philipwalton.github.io/polyfill/ to create a polyfill specifically for the attribute selectors needed?

Or output classes instead of attributes?

**Comment by Snugug** [comment] 2014-04-29 13:02
As per [best practices](http://pointnorth.io/#states), states should be applied through data attributes, not classes, so I'm not going to do that. Additionally, that wouldn't solve the "only want to target `medium` at `medium` use case".

Polyfill is an interesting idea, but I'm not sure of its performance implications (I'm willing to bet it's similar to selectivizr) and the breadth of it's community support (I hadn't heard about it until your mention).

What about the current recommendation doesn't work for you?

**Comment by adrianosmond** [comment] 2015-03-12 16:37
Having had a play with this for a few days this issue is probably my biggest source of frustration (which in the grand scheme of things is quite a small frustration). Like with media queries, I think in the real world you'll find yourself building up style changes gradually as modules grow (or shrink) in width, rather than having completely separate layouts across all states. I think writing Sass like this will be common:

```
.module {
  ...
  &[data-eq-state="small"] {
    ...
  }
  &[data-eq-state="medium"],
  &[data-eq-state="large"] {
    ...
  }
}

...

.sub-module {
  ...
  [data-eq-state="small"] & {
    ...
  }
  [data-eq-state="medium"] &,
  [data-eq-state="large"] & {
    ...
  }
}
```

In this scenario when you decide you want to add an x-large size that's mostly the same as medium and large, you have to go and find all the medium and large blocks and update them. Not a lot of work one you have one sub-module, but when you have many it's a bit of a pain.

Since accessing the DOM is slow and you don't want to have to add or remove a whole load of states every time you resize, I wonder if coming at a solution from a different angle would be a good plan? Instead of trying to fix this in the JavaScript, could it instead be fixed in the Sass mixin? Adding mixins like eq-gt and eq-lt (greater than and less than) would reduce the effort associated with adding or removing states, and probably make the code a little DRYer.

I'd be happy to do this if it sounds like a good idea?

**Comment by Snugug** [comment] 2015-03-12 17:42
The eq mixin allows you to specify multiple states you'd like styling to apply to, let me know if that works.

**Comment by adrianosmond** [comment] 2015-03-12 18:22
Yeah, I've seen that. The problem is that you have to state them explicitly like so:

```
@include eq('small', 'medium', 'large') {
      ...
}
```

I found that in my tests of the plugin I had one major "breakpoint" where things went from a largely vertical to a more horizontal layout at what I'd called "medium" size. This meant that my code was littered with 

```
@include eq('medium', 'large') {
      ...
}
```

Then when I added an 'x-large' size I had to go through and replce them all with

```
@include eq('medium', 'large', 'x-large') {
      ...
}
```

I'm proposing that something like

```
@include eq-gt('medium') {
      ...
}
```

could serve the same purpose (semantically that should probably be gte here), allowing you to target multiple states in one mixin, therefore eliminating the need to go back and add and remove states from the mixin. Getting a layout working based on element queries involved a lot of little tweaks when I tried it, to both the number of states and the width at which states kicked in, so making this authoring stage as painless as possible would be a good thing.

Do you get where I'm coming from or have I not done a good job of explaining myself?

**Comment by Snugug** [comment] 2015-03-12 18:51
I do, just don't see how you'd implement it without explicitly knowing all of the sizes somewhere. If you'd like to propose a solution I'll take a look but it needs to work in IE8+ and with both the CSS syntax and the HTML syntax

**Comment by adrianosmond** [comment] 2015-03-12 22:48
The aim would be to get the CSS exactly the same as it is currently, so the IE thing wouldn't be an issue. I'll have a go and let you take a look and see what you think.

**Comment by adrianosmond** [comment] 2015-03-13 17:19
How would you feel about defining a map at the top of _eq.scss:

```
$eq-modules: ();
```

Then every time you create a new module you add to the map like so:

```
$eq-modules: define-eq-module(module, (small, medium, large) );
```

Where define-eq-module would be something like

```
@function define-eq-module($module-name, $states) {
    @return map-merge($eq-modules, ($module-name: $states));
}
```

You'd only have to do that once per module, and then you'd know what the states were in order to be able to do eq-gt and eq-lt. Seems a little DRYer than what we have at the moment?

**Comment by Snugug** [comment] 2015-03-13 17:38
Not a fan. For HTML it means the definitions are decoupled and need to be updated independently, a source of error, and for CSS it decoupled the definitions from the modules

**Comment by adrianosmond** [comment] 2015-03-14 11:43
You wouldn't specify the sizes of the states in your sass, just the names. This is no different to how it works at the moment:

```
eq('small', 'medium', 'large')
```

is relying on exactly the same information, isn't it? Could you be more specific about a situation where it proves to be more of a source of error than what you currently have, so that I can understand where you're coming from?

**Comment by Snugug** [comment] 2015-03-14 12:07
While they look similar, there's a pretty big syntactical difference between the two and it's that difference that concerns me.

With `eq`, what you're saying is "I want to apply this styling here". It's an action statement. I'm going to do something right now, no setup required.

With `define-eq-modules`, what you're saying is "I have a module and it has these states". It's a passive statement. I'm going to do something with this later, but for now hold tight.

The reason I dislike the later is it's statement, "I have a module and it has these states", is now duplicated, either from the HTML or from the `eq-pts` mixin. It has a much higher potential to cause confusion with users about where they are defining the states.

The other concern I have is the specifying of a module. That is an entirely new concept for `eq.js` and one that will cause confusion amongst users. I, for instance, would expect if I call a module's `small` state that it would only apply when that 'module' has a `small` state applied. But that's not what you're doing, what you're doing is just applying the `small` state, which may be the state name of a parent node and your styling may be applied to that.

This all being said, I recently did some more digging into the initial question, and I think I may be able to support the original request with my original concerns. Just need to write up a few test cases, but if it works I may be able to implement something.

**Comment by adrianosmond** [comment] 2015-03-14 13:30
I think it's important to be able to use eq.js in conjunction with modular CSS. If you look at some of the early work that's going on in trying to create a stanardised solution for element queries in browsers, there's a lot of talk of modules: http://responsiveimagescg.github.io/eq-usecases/

Again, I think you've lost me here: 

>  I, for instance, would expect if I call a module's small state that it would only apply when that 'module' has a small state applied. But that's not what you're doing, what you're doing is just applying the small state, which may be the state name of a parent node and your styling may be applied to that.

I would also expect that it would only apply when the module has a small state applied. Each module would have its own set of states and a page could be made of many modules 

If you look at figure 1 in the link above, that would be an example of a module for me. I'd put the data-eq-pts on the div (or section or whatever) that has the border. I wouldn't want to put data-eq-points on anything that sits under that in the DOM as that would put extra load on the browser.

**Comment by Snugug** [comment] 2015-03-14 14:26
Having something that works with modular CSS and having something dependent on the concept of a module are two different things. **eq.js** aims to be the former, not the later.

In the proposed solution, the module proposed is a false construct; **eq.js** doesn't depend on a specific style of writing CSS for you to be able to use if. I presume the input for `$module` would either be a human-readable name (in which case our mixin would need to include what module you're working with as an argument, and my previous statement about having that module's state not necessarily be accurate holds), or it would be a selector and we would match against it, preventing users from being able to use it with anything and potentially failing in unexpected ways (slight typo in selector hard to track down, wanting to apply it to an attribute version of the selector instead of a fully qualified class, etc…). Either way, it's not something I'm willing to bring in as it pushes **eq.js** away from its core and introduces many potential pitfalls.

**Comment by adrianosmond** [comment] 2015-03-14 17:33
I take your point about having to work with all styles of CSS writing. I like BEM and it's sometimes hard to think of doing it any other way :)

I still don't think you've really explained what you mean about a module's state being not necessarily accurate. I'm sure you're right, as you've definitely thought about this more than I have, but you may've skipped a couple of steps in your explanation... If you have time to explain with a very quick HTML/CSS example that'd be great. If not, thanks for all the time you've put in!

**Comment by Snugug** [comment] 2015-03-15 20:54
I can do that. Let's take, for example, using using string names for module names (as opposed to exact selector matching).

``` scss
@include define-eq-module('message', 'small' 'medium' 'large');

.foo {
  @include eq-gt('message', 'medium') {
    content: bar;
  }
}
```

What you'd get is:

``` css
.foo[data-eq-state='medium'],
.foo[data-eq-state='large'] {
  content: bar;
}
```

But that's not intrinsically connected to the concept of the "message" module. If we tie it to existing inside the selector name, then we get something like this:

``` scss
@include define-eq-module('message', 'small' 'medium' 'large');

.foo {
  @include eq-gt('medium') {
    content: bar;
  }
}
```

Which produces nothing. But worse, if we have something like the following all sorts of things mess up:

``` scss
@include define-eq-module('message', 'small' 'medium' 'side by side');
@include define-eq-module('warning-message', 'small' 'side by side' 'medium' 'large');

.message {
  @include eq-gt('medium') {
    content: bar;
  }
}

.warning-message {
  @include eq-gt('medium') {
    content: qux;
}
```

If we do loose matching, we get the `message` module's styling applied to `warning-message`, which means styles will apply before we ant them to. If we do strict matching, any legitimate times we want a sub-class of message to have those states applied, we wouldn't be able to.

This seems like a convoluted edge case, but when you use semantic names instead of small, medium, and large, it starts to become something potentially harmful. Of course, neither of these things will work with more generic ways of selecting, like tags or raw selectors.

**Comment by adrianosmond** [comment] 2015-03-16 14:25
Right. I'm with you. I was imagining the former, not the latter. I think it works for me, but I can see how accidental misuse is more of a concern in the wider scheme of things. Thanks for taking the time to explain. I look forward to trying the JS based solution!

**Closed as completed** 2015-04-05 23:29 UTC
